version: "3"

services:
  db:
    image: mysql:latest
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_HOST: ${MYSQL_HOST}
      - MYSQL_USER: ${MYSQL_USER}
      - MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      - DOCKER_HOST_IP: ${DOCKER_HOST_IP}
    volumes:
      - /secure/node/config/.env:/Users/suhhyun/Projects/Nimo/node/config/.env

  backend-dev:
    depends_on:
      - db
    image: nimovaccine/nimo-server-dev:dev
    container_name: backend-dev
    hostname: backend-dev
    expose:
      - "3000"

      
    