version: "3"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"    
    networks:
      - app-tier
    env_file: .env   
    environment:
      MYSQL_DATABASE: ${SEQUELIZE_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_PASSWORD: ${SEQUELIZE_PASSWORD}
      MYSQL_USER: admin
      MYSQL_PASSWORD: ${SEQUELIZE_PASSWORD}
      MYSQL_ROOT_HOST: ${HOST}

  backend-dev:
    depends_on:
      - db
    image: nimovaccine/nimo-server-dev:dev
    container_name: backend-dev
    hostname: backend-dev
    expose:
      - "3000"